### ISSUE TITLE
ImportError: attempted relative import with no known parent package

### ISSUE THREAD

**Issue by atodorov** [RedHatQE/widgetastic.patternfly4#127]
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib64/python3.6/runpy.py", line 142, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/lib64/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/iqe_venv/lib64/python3.6/site-packages/pytest/__init__.py", line 3, in <module>
    from . import collect
  File "/iqe_venv/lib64/python3.6/site-packages/pytest/collect.py", line 8, in <module>
    from _pytest.deprecated import PYTEST_COLLECT_MODULE
  File "/iqe_venv/lib64/python3.6/site-packages/_pytest/deprecated.py", line 13, in <module>
    from _pytest.warning_types import PytestDeprecationWarning
  File "/iqe_venv/lib64/python3.6/site-packages/_pytest/warning_types.py", line 6, in <module>
    import attr
  File "/iqe_venv/lib64/python3.6/site-packages/attr/__init__.py", line 5, in <module>
    from . import converters, exceptions, filters, validators
  File "/iqe_venv/lib64/python3.6/site-packages/attr/converters.py", line 7, in <module>
    from ._make import NOTHING, Factory
  File "/iqe_venv/lib64/python3.6/site-packages/attr/_make.py", line 13, in <module>
    from ._compat import (
  File "/iqe_venv/lib64/python3.6/site-packages/attr/_compat.py", line 3, in <module>
    import platform
  File "/usr/lib64/python3.6/platform.py", line 116, in <module>
    import sys, os, re, subprocess
  File "/usr/lib64/python3.6/subprocess.py", line 137, in <module>
    import select
  File "/iqe_venv/lib/python3.6/site-packages/widgetastic_patternfly4/select.py", line 3, in <module>
    from .dropdown import Dropdown
ImportError: attempted relative import with no known parent package
```

My code is

```
from widgetastic_patternfly4 import Select

release_dropdown = Select()
```

**Comment by quarckster** [comment]
Unable to reproduce.

**Comment by atodorov** [comment]
This is still a problem for me so please don't close it.

**Comment by quarckster** [comment]
This problem could be caught in CI but `test_select.py` passed in https://github.com/RedHatQE/widgetastic.patternfly4/runs/4006908977?check_suite_focus=true. I suspect that the issue is in your environment.

**Comment by atodorov** [comment]
Found the cause, pws was `/iqe_venv/lib64/python3.6/site-packages/widgetastic_patternfly4` which messed up the relative imports.
